### ISSUE TITLE
Run first demo WorldCereal-based extraction use case

### ISSUE THREAD

**Issue by kvantricht** [Open-EO/openeo-gfmap#43]
Using demo dataset from #40 and writing documentation along the way in #42 .

**Comment by kvantricht** [comment]
@GriffinBabe, my initial review of test extractions:

<h3>S2 file “S2_at2021lpis809720_32633_2020-08-30_2022-03-03”</h3>

•	In general, we should maybe ask for feedback from Daniele and both Jeroens on the files too
•	“mask_scl_dilation” mask not present in file; we cannot generate it afterwards
•	Some more metadata in file could be useful (such as extraction date, job launch user, title, description, mentioning GFMAP, resolution, start_date, end_date
•	S2 dtype is Int16, why not UINT16? (which would require different nodata value which is now at -32767)
•	What rule was used (if any) to drop observations that are certainly completely clouded?
•	First file I opened in QGIS has corrupt “-1” values around two borders. This value is not the no-data value so will be treated as valid which is problematic.
 ![image](https://github.com/Open-EO/openeo-gfmap/assets/66418796/f1bc214f-93a0-42a5-bb17-0ec551bf4c2e)

•	Maybe related to this, we end up now with a 65X65 file which could be a bit inconvenient. Probably we should have 64X64
•	SCL band is also INT16: could we in a post-job action change this to UINT8 to save storage or would that be too complex and not really worth it?
•	File name pattern should probably contain the resolution (and maybe patch size? Not sure).

<h3>AUX file “AUX_at2021lpis809720_32633_2020-08-30_2022-03-03”</h3>

•	Should we replace “AUX” by “WORLDCEREAL”?
•	File is wrongly georeferenced. Needs new check once this is fixed.
•	Variable now called “CROPTYPE” while it doesn’t always contain crop type information. Just landcover is also possible. Maybe “LABEL” 
•	Same comment about the 65X65 dimensions
•	Same comment about some metadata that could be useful
•	Where does the attribute “landcover_label” come from?
•	Is it normal that “confidence” attribute is None?
•	Are we sure UINT16 covers the entire possible range of values? 
•	There is no no-data value specified in the file. Which one do you use in rasterization process? Should be encoded as such in the netcdf so it’s handled properly downstream.
•	File name pattern should probably contain the resolution (and maybe patch size? Not sure).
•	Why is attribute “institution” still there and pointing to openEO platform Geotrellis backend? I think no OpenEO backend is involved in this file creation?

**Comment by GriffinBabe** [comment]
Already an answer to a couple of your points, I'm running a new extraction with some changes before answering to the others

> • What rule was used (if any) to drop observations that are certainly completely clouded?

No strategy currently present, I think an easy one would be to drop observations with a cloud percentage higher than, let's say, 95% ? This can be done directly from the OpenEO load_collection feature


> • SCL band is also INT16: could we in a post-job action change this to UINT8 to save storage or would that be too complex and not really worth it?

Probably not worth it, because you might save only half the space of one on the 13 bands. Also it's nice for later processing to have everything aligned on the same resolution, since anyways SCL is gonna be used for pixelwise operations on the optical data


> • File name pattern should probably contain the resolution (and maybe patch size? Not sure).

I don't think it's necessary as all the tiles should be consistent within an extraction process


> • Where does the attribute “landcover_label” come from?

It's something from the input dataset, but I can remove this because it's almost the same value for each sample


> • Is it normal that “confidence” attribute is None?

It's also extracted from the input dataset, and it's None already from there for all samples


> • There is no no-data value specified in the file. Which one do you use in rasterization process? Should be encoded as such in the netcdf so it’s handled properly downstream.

Could you indicate me where is the list of the harmonized labels? This is decided by the user, but in the context of WorldCereal it should be matching the harmonized labels maximum value. Alternatively we can also put in to int64, which will accept negative values and can go on a very high range, it's still remaining a small file as such as it is only a 2D array (1 band, no time)


> • There is no no-data value specified in the file. Which one do you use in rasterization process? Should be encoded as such in the netcdf so it’s handled properly downstream.

Yes indeed, I will add this as _FillValue as it seems to be the convention with NetCDF files ([this source](https://pro.arcgis.com/en/pro-app/3.1/help/data/multidimensional/missing-data-in-netcdf-data.htm#:~:text=Two%20attributes%2C%20missing_value%20and%20_FillValue,depending%20on%20where%20they%20appear.) and in my past experiences)

**Comment by GriffinBabe** [comment]
Another question: how do you want the rasterization? With the `all_touched` parameter set to `True` or to `False`?

**Comment by kvantricht** [comment]
> No strategy currently present, I think an easy one would be to drop observations with a cloud percentage higher than, let's say, 95% ? This can be done directly from the OpenEO load_collection feature

As a minimum, indeed good to have this added. We could make it configurable in GFMAP?

> I don't think it's necessary as all the tiles should be consistent within an extraction process

Not sure about this, I think we would prefer to extract S1 at 20m and meteo even at much lower resolution. This saves a lot of storage. Downstream OpenEO-based processing will finally merge the cubes.

> It's something from the input dataset, but I can remove this because it's almost the same value for each sample

Should not always be the same. `11` means cropland, but there will be other datasets (not the one I sent) which have other landcovers as well. But the crucial thing here is that this attribute only belongs to the center point/field we used and it doesn't necessarily fit the rest of the pixels in the rasterized patch. So I would omit this attribute as it will be confusing.

> It's also extracted from the input dataset, and it's None already from there for all samples

Interesting. I guess once we use the API, this shouldn't be None. So let's worry about it later.

> Could you indicate me where is the list of the harmonized labels? This is decided by the user, but in the context of WorldCereal it should be matching the harmonized labels maximum value. Alternatively we can also put in to int64, which will accept negative values and can go on a very high range, it's still remaining a small file as such as it is only a 2D array (1 band, no time)

The possible values are in the first column of [this file](https://vitoresearch.sharepoint.com/:x:/r/sites/21717-ccn-world-cereal/Shared%20Documents/Research%20and%20Development/Legend/WorldCereal_LC_CT_legend_v2.xlsx?d=wfdff473328e14450add4221b170b744c&csf=1&web=1&e=RZgqOG). Note that this is a string for readability and we should strip all `-` signs to get to the integer. I think `int64` is indeed what is normally used for the new legend.

> Another question: how do you want the rasterization? With the all_touched parameter set to True or to False?

As discussed, `all_touched` should be `False`

**Comment by kvantricht** [comment]
@GriffinBabe 
- [ ] Todo: file a bug report for OpenEO on the -1 border issue with tehe extractions

**Comment by GriffinBabe** [comment]
Issue reported: https://github.com/Open-EO/openeo-geopyspark-driver/issues/712

**Comment by GriffinBabe** [comment]
Except for the scl problem, all is solved here. I created a ticket in WorldCereal technical and open-eo geopyspark driver
https://github.com/Open-EO/openeo-geopyspark-driver/issues/715

#45 closes it
